// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8rXUdn_lpGKVWV7iGdiEXb4lueFg_9-Q',
    appId: '1:158873137678:web:c5334d51a88ae0a4e6425f',
    messagingSenderId: '158873137678',
    projectId: 'school-manager-793a1',
    authDomain: 'school-manager-793a1.firebaseapp.com',
    storageBucket: 'school-manager-793a1.appspot.com',
    measurementId: 'G-JTBJDGFZVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSqAR2NDAdrkS3RuIGTQI0535DucY0VmY',
    appId: '1:158873137678:android:ac4a8ad2c40fea49e6425f',
    messagingSenderId: '158873137678',
    projectId: 'school-manager-793a1',
    storageBucket: 'school-manager-793a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaVgIsihMw_49-VJ3nZMGZeIHF-ggCp_o',
    appId: '1:158873137678:ios:22efad56e5059ba9e6425f',
    messagingSenderId: '158873137678',
    projectId: 'school-manager-793a1',
    storageBucket: 'school-manager-793a1.appspot.com',
    iosBundleId: 'com.example.schoolWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaVgIsihMw_49-VJ3nZMGZeIHF-ggCp_o',
    appId: '1:158873137678:ios:e51c3a35355e5168e6425f',
    messagingSenderId: '158873137678',
    projectId: 'school-manager-793a1',
    storageBucket: 'school-manager-793a1.appspot.com',
    iosBundleId: 'com.example.schoolWeb.RunnerTests',
  );
}
